In [1]:
import torch,numpy as np,sympy as sm
import matplotlib.pyplot as plt


In [2]:
scalar = np.array([1,2,3,4,5])
scalar

array([1, 2, 3, 4, 5])

## practicing pytorch basic to advance 

In [3]:

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


In [5]:
arr1d = torch.tensor([1,2,3])
arr1d # printing to console 

torch.is_tensor(arr1d) #checking tensor or not

a = torch.asarray(arr1d)
b = torch.asarray([5,6,7,8]) # using asarray() method to create tensor 
a
b

#creating zeros tensor using torch.zero() method 

Zeros = torch.zeros(2,3)
Zeros

c = torch.ones(5,5)
c

#creating tensor from numpy array 
ndarr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

d = torch.from_numpy(ndarr)
d

#using torch.range() or torch.arange() methdo to create tensor 

f = torch.arange(50,100, dtype=torch.float32)
f**2

#using torch.linspace 
g = torch.linspace(1,10, steps=5)
g

#creating empty tensor 
h = torch.empty((2,3), dtype=torch.float16)
h

tensor([1, 2, 3])

True

tensor([1, 2, 3])

tensor([5, 6, 7, 8])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

tensor([2500., 2601., 2704., 2809., 2916., 3025., 3136., 3249., 3364., 3481.,
        3600., 3721., 3844., 3969., 4096., 4225., 4356., 4489., 4624., 4761.,
        4900., 5041., 5184., 5329., 5476., 5625., 5776., 5929., 6084., 6241.,
        6400., 6561., 6724., 6889., 7056., 7225., 7396., 7569., 7744., 7921.,
        8100., 8281., 8464., 8649., 8836., 9025., 9216., 9409., 9604., 9801.])

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

tensor([[   0.0000,    0.0000, -120.2500],
        [   2.7949,    0.0000,    0.0000]], dtype=torch.float16)

In [ ]:
ab